export const TYPES = {
  Http: Symbol.for('Http'),
  UserRepository: Symbol.for('UserRepository'),
  Console: Symbol.for('Console'),
  Logger: Symbol.for('Logger'),
  Window: Symbol.for('Window'),
  Document: Symbol.for('Document'),
  Selector: Symbol.for('Selector'),
  WebPage: Symbol.for('WebPage'),
  MutationObserver: Symbol.for('MutationObserver'),
  State: Symbol.for('State'),
  StateStrategy: Symbol.for('StateStrategy'),
  Database: Symbol.for('Database'),
  SizesStrategy: Symbol.for('SizesStrategy'),
}
