export const TYPES = {
  Http: Symbol.for('Http'),
  Console: Symbol.for('Console'),
  Connector: Symbol.for('Connector'),
  Logger: Symbol.for('Logger'),
  Window: Symbol.for('Window'),
  Document: Symbol.for('Document'),
  Selector: Symbol.for('Selector'),
  WebPage: Symbol.for('WebPage'),
  MutationObserver: Symbol.for('MutationObserver'),
  State: Symbol.for('State'),
  StateStrategy: Symbol.for('StateStrategy'),
  Database: Symbol.for('Database'),
  SizesStrategy: Symbol.for('SizesStrategy'),
  EmotionsRepository: Symbol.for('EmotionsRepository'),
  EmotionsCanBeUpdatedUseCase: Symbol.for('EmotionsCanBeUpdatedUseCase'),
  EmotionsListUseCase: Symbol.for('EmotionsListUseCase'),
}
